champdict={
    "Garen":        {"Species":"Male"       , "Nation":"Demacia"    ,"Position":"Top"       ,"Resource":"No Mana"   ,"Range":"Melee"},
    "Katarina" :    {"Species":"Female"     , "Nation":"Noxus"      ,"Position":"Mid"       , "Resource":"No Mana"  , "Range":"Melee"},
    "Zac" :         {"Species":"Creature"   , "Nation":"Zaun"       ,"Position":"Jungle"    , "Resource":"Health"   , "Range":"Melee"},
    "Akali" :       {"Species":"Female"     , "Nation":"Ionia"      ,"Position":"Mid"       , "Resource":"Energy"   , "Range":"Melee"},
    "Aatrox" :      {"Species":"Darkin"     , "Nation":"Shurima"    ,"Position":"Top"       , "Resource":"No Mana"  , "Range":"Melee"},
    "Ashe" :        {"Species":"Female"     , "Nation":"Freljord"   ,"Position":"ADC"       , "Resource":"Mana"     , "Range":"Ranged"},
    "Gangplank" :   {"Species":"Male"       , "Nation":"Bilgewater" ,"Position":"Top"       , "Resource":"Mana"     , "Range":"Melee"},
    "Kai'sa" :      {"Species":"Female"     , "Nation":"Void"       ,"Position":"ADC"       , "Resource":"Mana"     , "Range":"Ranged"},
    "Leona" :       {"Species":"Female"     , "Nation":"Targon"     ,"Position":"Support"   , "Resource":"Mana"     , "Range":"Melee"},
    "Lulu" :        {"Species":"Female"     , "Nation":"Bandle"     ,"Position":"Support"   , "Resource":"Mana"     , "Range":"Ranged"},
    "Samira" :      {"Species":"Female"     , "Nation":"Noxus"      ,"Position":"ADC"       , "Resource":"Mana"     , "Range":"Ranged,Melee"},
    "Qiyana" :      {"Species":"Female"     , "Nation":"Ixtal"      ,"Position":"Mid"       , "Resource":"Mana"     , "Range":"Melee"},
    "Talon" :       {"Species":"Male"       , "Nation":"Noxus"      ,"Position":"Mid"       , "Resource":"Mana"     , "Range":"Melee"},
    "Tryndamere" :  {"Species":"Male"       , "Nation":"Freljord"   ,"Position":"Top"       , "Resource":"Rage"     , "Range":"Melee"},
    "Viego" :       {"Species":"Male"       , "Nation":"ShadowIsles","Position":"Jungle"    , "Resource":"No Mana"  , "Range":"Melee"},
    "Taric" :       {"Species":"Male"       , "Nation":"Targon"     ,"Position":"Support"   , "Resource":"Mana"     , "Range":"Melee"},
    "Viktor" :      {"Species":"Male"       , "Nation":"Zaun"       ,"Position":"Mid"       , "Resource":"Mana"     , "Range":"Ranged"},
    "Azir" :        {"Species":"Male"       , "Nation":"Shurima"    ,"Position":"Mid"       , "Resource":"Mana"     , "Range":"Ranged"},
    "Diana" :       {"Species":"Female"     , "Nation":"Targon"     ,"Position":"Jungle,Mid", "Resource":"Mana"     , "Range":"Melee"},
}